### ISSUE TITLE
 "Couldn't add resources"

### ISSUE THREAD

**Issue by okicarde** [harryeffinpotter/SACM#1]
When building .exe it fails here with a "Couldn't add resources", then if I try to run SACM.exe it closes inmediatly, what can i do ?
Im on W11, did run both files with and without admin privileges. 

Creating EXE
Filename: C:\Users\octav\OneDrive\Desktop\SACM-master\bin\SACM.exe
Exe-Format: 32 Bit | Console (Visible)
Adding icon...OK
Adding resources...
Error: Couldn't add resources
Press any key to continue . . .

**Comment by harryeffinpotter** [comment]
> When building .exe it fails here with a "Couldn't add resources", then if I try to run SACM.exe it closes inmediatly, what can i do ? Im on W11, did run both files with and without admin privileges.
> 
> Creating EXE Filename: C:\Users\octav\OneDrive\Desktop\SACM-master\bin\SACM.exe Exe-Format: 32 Bit | Console (Visible) Adding icon...OK Adding resources... Error: Couldn't add resources Press any key to continue . . .

i honestly... dont know, do you want to get in a call with me on discord? I can help you fix it if youre planning on adding fedatures/forking.

YouStayGold is my discord name. sorry for the delayed response  I never check my inbox on here!

**Comment by harryeffinpotter** [comment]
oh god, get it out of the OneDrive folder, that might be part of the issue. pick somewhere actually local, not in dreaded one drive. and do yourself a favor and remove one drive, please. there are probably plenty of scripts to help you fix your directories afterward, and if not there are definitely many guides. Let me know if that helps, if not hit me up on discord. thanks.

**Comment by okicarde** [comment]
Omg it was actually because of Onedrive LOL thanks.
Sorry for late response, I never check this.
